language: node_js
node_js:
  - "12"
  - "10"

cache: yarn

install:
  - 'if [ -n "${PACKAGE-}" ]; then cd "packages/${PACKAGE}"; fi'
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test

sudo: false

branches:
  only:
    - master

env:
  matrix:
    - 'PACKAGE=eslint-config-1pete'
    - 'PACKAGE=eslint-config-1pete-react'

matrix:
  include:
    - node_js: "lts/*"
      env: ''
